- name: Provision with Ansible
  hosts: all
  become: yes

  vars:
    services_info: |
      Jenkins URL - http://localhost:8080/jenkins/
      Jenkins Delivery - http://localhost:8080/jenkins/view/Pet%20CD/
      Application URL - http://localhost:8080/mnt-lab/

  pre_tasks:
  - debug: msg="Let's do this"

  roles:
  - java
  - jenkins
  - tomcat
  - web

  tasks:
  - name: JAVA | install
    yum: name=java-1.7.0-openjdk-devel

  - name: REPO | add nginx-repo
    yum:
      name: http://nginx.org/packages/rhel/6/noarch/RPMS/nginx-release-rhel-6-0.el6.ngx.noarch.rpm

  - name: NGINX | install nginx
    yum:
      name: nginx

  - name: NGINX | start nginx
    service:
      name: nginx
      state: started

  - name: TOMCAT | download and unarchive
    unarchive: src=http://ftp.byfly.by/pub/apache.org/tomcat/tomcat-7/v7.0.70/bin/apache-tomcat-7.0.70.tar.gz
               dest=/opt
               remote_src=yes
               copy=no

  - name: TOMCAT | symlink install directory
    file: src=/opt/apache-tomcat-7.0.70 path=/usr/share/tomcat state=link

  - name: TOMCAT | place server.xml
    copy: src=resources/server.xml dest=/opt/apache-tomcat-7.0.70/conf/

  - name: TOMCAT | init script
    copy: src=resources/tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

  - name: TOMCAT | start tomcat
    service: name=tomcat state=started enabled=yes

  - name: JENKINS | get jenkins repo
    command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo

  - name: JENKINS | import key
    command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: JENKINS | install
    yum: name=jenkins state=latest

  - name: JENKINS | start jenkins
    service:
      name: jenkins
      state: started

  post_tasks:
  - debug: var=services_info.split('\n')
