- name: Provision with Ansible
  hosts: all
  become: yes

  vars:
    services_info: |
      Jenkins URL - http://localhost:8080/jenkins/
      Jenkins Delivery - http://localhost:8080/jenkins/view/Pet%20CD/
      Application URL - http://localhost:8080/mnt-lab/

  pre_tasks:
  - debug: msg="Let's do this"

  tasks:

  - name: Installing NGINX repo rpm
    yum: "name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm"
  - name: downloading jenkins repo
    get_url: url=http://pkg.jenkins.io/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
  - name: jenkins repo key
    rpm_key: state=present key=http://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Instaling packages
    yum: name={{ item.name }} state={{ item.state| default("latest") }}
    with_items: 
      - {name: "java-1.7.0-openjdk-devel", state: present}
      - {name: nginx} 
      - {name: tomcat} 
      - {name: jenkins} 
      - {name: git}
      - {name: tomcat-webapps}

  - name: changing nginx config
    copy: src=virtual.conf dest=/etc/nginx/conf.d/virtual.conf
  - name: NGINX | Starting NGINX
    service: name=nginx state=started enabled=yes

  - name: copying tomcat config
    copy: src=server.xml dest=/usr/share/tomcat/conf/server.xml
  - name: Starting Tomcat
    service: name=tomcat state=started enabled=yes

  - name: changing jenkins group
    user: name=jenkins groups=tomcat
  - name: Copy config
    template: src=jenkins dest=/etc/sysconfig/jenkins
  - name: cp xml
    template: src=config.xml dest=/var/lib/jenkins/config.xml owner=jenkins group=jenkins
  - name: copying plugins
    copy: src=plugins dest=/var/lib/jenkins owner=jenkins group=jenkins force=no
  - name: copy maven
    copy: src=hudson.tasks.Maven.xml dest=/var/lib/jenkins/ owner=jenkins group=jenkins force=no
  - name: Jobs for Jenkins
    copy: src=jobs dest=/var/lib/jenkins force=no
  - name: chown
    file: path=/var/lib/jenkins owner=jenkins group=jenkins recurse=yes
  - name: jenkins start
    service: name=jenkins state=started enabled=yes

  post_tasks:
  - debug: var=services_info.split('\n')
