- name: Provision with Ansible
  hosts: all
  sudo: yes
  
  tasks:
   - debug: msg="Will install Java"
   - name: Ensure Java is installed.
     yum: name=java-1.7.0-openjdk-devel state=installed

   - name: Install git
     yum: name=git state=latest

   - debug: msg="Will install Nginx" 
   - name: Install nginx
     yum: name=nginx state=latest

   - name: Copy config
     template: src=default.conf dest=/etc/nginx/conf.d/default.conf

   - debug: msg="Will install tomcat"
   - name: Install tomcat
     yum: name=tomcat state=present

   - name: Changing ownership of Tomcat's directory
     file: path=/var/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

   - name: Copy server.xml
     template: src=server.xml dest=/etc/tomcat/server.xml

   - name: Install tomcat-webapps
     yum: name=tomcat-webapps state=present
   
   - name: jenkins wget
     command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    
   - name: jenkins rpm
     command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
   - name: jenkins install
     yum: name=jenkins state=present
   
   - name: change jenkins port
     template: src=jenkins dest=/etc/sysconfig/jenkins
     
   - name: fff
     template: src=config.xml dest=/var/lib/jenkins/config.xml

   - name: Copying Jenkins-user sudoers file
     copy: src=jenkins-user dest=/etc/sudoers.d/ force=no
   
   - name: Copying Maven config for Jenkins
     copy: src=hudson.tasks.Maven.xml dest=/var/lib/jenkins/ force=no

   - name: Jobs for Jenkins
     copy: src=jobs dest=/var/lib/jenkins/ force=no

   - name: Plugins for Jenkins
     copy: src=plugins dest=/var/lib/jenkins/ force=no

   - name: Changing Jenkins home directory ownership
     file: path=/var/lib/jenkins owner=jenkins group=jenkins state=directory recurse=yes

   - name: Starting Jenkins
     service: name=jenkins state=started enabled=yes

   - name: Start nginx
     service: name=nginx state=running

   - name: Start tomcat
     service: name=tomcat state=running









