- name: Provision with Ansible
  hosts: all
  become: yes

  vars:
    services_info: |
      Jenkins URL - http://localhost:8080/jenkins/
      Jenkins Delivery - http://localhost:8080/jenkins/view/Pet%20CD/
      Application URL - http://localhost:8080/mnt-lab/

  pre_tasks:
  - debug: msg="Let's do this"

  tasks:
  - name: Instaling Java
    yum: "name=java-1.7.0-openjdk-devel state=present"

  - name: Installing NGINX repo rpm
    yum: "name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm"
  - name: Installing NGINX
    yum: name=nginx state=latest
  - name: changing nginx config
    copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
  - name: NGINX | Starting NGINX
    service: name=nginx state=started enabled=yes

  - name: Installing Tomcat
    yum: name=tomcat state=latest
  - name: copuing tomcat config
    copy: src=server.xml dest=/usr/share/tomcat/conf/server.xml
  - name: Starting Tomcat
    service: name=tomcat state=started enabled=yes

  - name: jenkins repo key
    rpm_key: state=present key=http://pkg.jenkins.io/redhat-stable/jenkins.io.key
  - name: downloading jenkins repo
    get_url: url=http://pkg.jenkins.io/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
  - name: jenkins install
    yum: name=jenkins state=latest
  - name: jenkins start
    service: name=jenkins state=started enabled=yes

  post_tasks:
  - debug: var=services_info.split('\n')
