- name: Provision with Ansible
  hosts: all
  sudo: yes
  
  tasks:
   - name: Ensure Java is installed.
     yum: name=java-1.7.0-openjdk-devel state=installed

   - name: Installing git
     yum: name=git state=latest
 
   - name: Installing nginx
     yum: name=nginx state=latest

   - name: Copying nginx config
     template: src=res/default.conf dest=/etc/nginx/conf.d/default.conf

   - name: Install tomcat
     yum: name=tomcat state=present

   - name: Changing ownership of Tomcat's directory
     file: path=/var/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

   - name: Copy server.xml
     template: src=res/server.xml dest=/etc/tomcat/server.xml

   - name: Install tomcat-webapps
     yum: name=tomcat-webapps state=present
   
   - name: jenkins wget
     command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    
   - name: jenkins rpm
     command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
   - name: jenkins install
     yum: name=jenkins state=present
   
   - name: Change jenkins port and prefix
     template: src=res/jenkins dest=/etc/sysconfig/jenkins
     
   - name: Change authorization
     template: src=res/config.xml dest=/var/lib/jenkins/config.xml

   - name: Copying user to sudoers file
     template: src=res/jenkins-user dest=/etc/sudoers.d/ force=no
   
   - name: Copying Maven config to Jenkins
     template: src=res/hudson.tasks.Maven.xml dest=/var/lib/jenkins/ force=no

   - name: Jobs for Jenkins
     template: src=res/jobs dest=/var/lib/jenkins/ force=no

   - name: Plugins for Jenkins
     template: src=res/plugins dest=/var/lib/jenkins/ force=no

   - name: Changing Jenkins home directory ownership
     file: path=/var/lib/jenkins owner=jenkins group=jenkins state=directory recurse=yes

   - name: Starting Jenkins
     service: name=jenkins state=started enabled=yes

   - name: Start nginx
     service: name=nginx state=running

   - name: Start tomcat
     service: name=tomcat state=running
