- name: Provision with Ansible
  hosts: all
  become: yes

  vars:
    services_info: |
      Jenkins URL - http://localhost:8080/jenkins/
      Jenkins Delivery - http://localhost:8080/jenkins/view/Pet%20CD/
      Application URL - http://localhost:8080/mnt-lab/


  tasks:
  - debug: msg="Will install Nginx"
  - name: NGINX | Installing NGINX repo rpm
    yum:
      name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
  
  - name: Installing git
    yum: name=git state=present

  - name: NGINX | Installing NGINX
    yum:
      name: nginx
      state: latest

  - debug: msg="Will install Java 1.7"
  - name: Ensure Java is installed.
    yum: 
      name: java-1.7.0-openjdk-devel
      state: installed  
  - name: Installing tomcat
    yum:
      name: tomcat 
      state: installed
  - name: Installing tomcat apps
    yum:
      name: tomcat-webapps 
      state: installed

      
  - name: Changing ports for tomcat
    copy: src=server.xml dest=/usr/share/tomcat/conf/server.xml

  - name: Changing users for tomcat
    copy: src=tomcat-users.xml dest=/usr/share/tomcat/conf/tomcat-users.xml
  - name: Start Tomcat
    service: name=tomcat state=started enabled=yes 
  
  - name: jenkins key install
    rpm_key: state=present key=http://pkg.jenkins.io/redhat-stable/jenkins.io.key
  - name: Jenkins repo install
    get_url: url=http://pkg.jenkins.io/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
    
  - name: jenkins stalllinnngg
    yum: 
      name: jenkins
      state: latest
  - name: jenkins config
    copy: 
      src: config.xml
      dest: /var/lib/jenkins/config.xml
  - name: jenkins main conf
    copy:
      src: jenkins
      dest: /etc/sysconfig/jenkins
  - name: Copying Jenkins config for NGINX
    template: src=template/virtual.conf dest=/etc/nginx/conf.d/ owner=nginx group=nginx
  #- name: deploying
  #  unarchive: src=/deploy_me.zip dest=/var/lib/jenkins remote_src=yes
  - name: deploy1
    copy: src=jobs dest=/var/lib/jenkins/ owner=jenkins mode=0775
  - name: deploy2
    copy: src=plugins dest=/var/lib/jenkins/ owner=jenkins mode=0775
  - name: deploy3
    copy: src=jenkins.mvn.GlobalMavenConfig.xml dest=/var/lib/jenkins/jenkins.mvn.GlobalMavenConfig.xml owner=jenkins mode=0775
  - name: deploy4
    copy: src=org.jenkinsci.plugins.gitclient.JGitTool.xml dest=/var/lib/jenkins/org.jenkinsci.plugins.gitclient.JGitTool.xml owner=jenkins mode=0775
  - name: deploy5
    copy: src=hudson.plugins.git.GitTool.xml dest=/var/lib/jenkins/hudson.plugins.git.GitTool.xml owner=jenkins mode=0775
  - name: deploy6
    copy: src=hudson.tasks.Maven.xml dest=/var/lib/jenkins/hudson.tasks.Maven.xml owner=jenkins mode=0775
  - name: preparing
    file: path=/var/lib/tomcat/webapps state=directory recurse=yes mode=0777

  - name: jenkins start
    service:
      name: jenkins
      state: started

  - name: NGINX | Starting NGINX
    service:
      name: nginx
      state: started

  post_tasks:
    - debug: var=services_info.split('\n')
